name: Dummy Test
'on':
  workflow_dispatch:

jobs:
  Unit_Tests:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout dummy
      uses: actions/checkout@v3
      with:
        repository: santander-group-europe/alm-dummy-app-ios
        token: ${{secrets.PAT}} # `PAT` is a secret that contains your PAT
    
