name: Dummy Test
'on':
  workflow_dispatch:

jobs:
  Unit_Tests:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout dummy
      uses: actions/checkout@v3
      with:
        repository: santander-group-europe/alm-dummy-app-ios@master
      # token: ${{secrets.PAT}} # `GH_PAT` is a secret that contains your PAT
    
    #- name: Action Test check input
     # id: checkinputs
     # run: "echo Se ha seleccionado '${{github.events.inputs.hello}}'"
      
    #- uses: santander-group-europe/test-spain-2022-action@master
     # name: Action Test        
     # id: actiontest
     # with:
      #  hello: "${{github.events.inputs.hello}}"
      #  tokenPAT: ${{ secrets.PAT }} # `GH_PAT` is a secret that contains your PAT
