name: Dummy Test
'on':
  workflow_dispatch:
  workflow_call:
    secrets:
      token:
       required: true
      application_id:
       required: true
      application_private_key:
       required: true

jobs:
  Checkout_Dummy:
    runs-on: ubuntu-latest
    steps:
    
    - name: Get Token Org Europe
      id: generateEuropeToken
      uses: peter-murray/workflow-application-token-action@v1.3.0
      with:
        application_id: ${{ secrets.application_id }}
        application_private_key: ${{ secrets.TOKEN_APP_ACTIONS_EUROPE }}
        organization: santander-group-europe
    
    - name: Checkout dummy
      uses: actions/checkout@v3
      with:
        repository: santander-group-europe/alm-dummy-app-ios@develop
        submodules: false
        ref: develop
        token: ${{ steps.generateEuropeToken.outputs.token }}
        #token: ${{secrets.PAT}} # `PAT` is a secret that contains your PAT  
        
 
