name: Dummy Test
'on':
  workflow_dispatch:
  workflow_call:
    secrets:
      token:
       required: true
      application_id:
       required: true
      application_private_key:
       required: true

# Running Unit test using MAC-OS 12 
jobs:
  unitTest:
    runs-on: macos-12
    steps:
    
    - name: Get Token Org Europe
      id: generateEuropeToken
      uses: peter-murray/workflow-application-token-action@v1.3.0
      with:
        application_id: ${{ secrets.APP_ID_ACTIONS_EUROPE }}
        application_private_key: ${{ secrets.TOKEN_APP_ACTIONS_EUROPE }}
        organization: santander-group-europe
          
    - name: Checkout dummy repo
      uses: actions/checkout@v3
      with:
        repository: santander-group-europe/alm-dummy-app-ios
        submodules: false
        ref: develop
        token: ${{ steps.generateEuropeToken.outputs.token }}
        
    # Fastalane Installation
    - uses: actions/checkout@v3
      name: Checkout Fastlane
      with:
        repository: santander-group-europe/alm-fastlane-framework
        ref: develop
        path: main
        token: ${{steps.generateEuropeToken.outputs.token}}

    - name: Installation Fastlane
      shell: bash
      run: |
        cp -R main/framework main/setup.rb main/Gemfile_Template .
        chmod +x setup.rb && ./setup.rb
        rm -f Gemfile_Template setup.rb
          
    - name: Apply xcode version (13.2.1)
      run: sudo xcode-select -switch /Applications/Xcode_13.2.1.app && /usr/bin/xcodebuild -version
        
    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2

    - name: Setup machine
      run: |
        bundle install
      
    - name: build
      run: |
        pod install
        bundle exec fastlane sonarQ_vostok
        cd sonar-reports
            
    - name: Rename coverage file
      run: |
        mv sonar-reports/sonarqube-generic-coverage.xml sonar-reports/coverage.xml
    
    - uses: actions/upload-artifact@v2.2.4
      name: Upload coverage file
      with:
        name: coverage
        path: sonar-reports/coverage.xml
        retention-days: 1
          
    - uses: actions/upload-artifact@v2.2.4
      name: Upload swiftlint file
      with:
        name: swiftlint
        path: sonar-reports/swiftlint.txt
        retention-days: 1

    - name: Get version
      run: |
         bundle exec fastlane getProjectVersion_vostok
           
    - name: Set output
      id: setOutputStep
      run: |
         echo "::set-output name=version::${{env.VERSION}}"    

  jobSonar:
    runs-on: [runner-openshift-oneapp-actions-spain]
    needs: [unitTest]
    
    steps:

      - name: Get Token Org Europe
        id: generateEuropeToken
        uses: peter-murray/workflow-application-token-action@v1.3.0
        with:
          application_id: ${{ secrets.application_id }}
          application_private_key: ${{ secrets.application_private_key }}
          organization: santander-group-europe
          
      - uses: actions/checkout@v3
        name: Checkout application repository
        with:
          repository: ${{ github.repository }}
          submodules: false
          ref: develop
          token: ${{ steps.generateEuropeToken.outputs.token }}
          
      - uses: actions/download-artifact@v2
        name: Download coverage artifact
        with:
          name: coverage
          path: sonar-reports
      
      - uses: actions/download-artifact@v2
        name: Download swiftlint artifact
        with:
          name: swiftlint
          path: sonar-reports
        
      - uses: santander-group-europe/alm-sonar-action@master
        name: run sonar
        id: runSonar
        with:
          projectVersion: ${{ needs.unitTests.outputs.version }}
          projectKey: "SANES:santander-group-europe:SUA:alm-dummy-app-ios"
          projectName: ${{ github.event.repository.name }}
          sourcesPath: "./"
          sonar_token: ${{ secrets.sonar_token_dummy_ios }}        
