name: GitHub Actions Goodbye
'on':
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: santander-group-europe/hello-world-composite-action@master
        with:
          who-to-greet: 'Pablo Picasso'
          hello: "${{github.events.inputs.hello}}"
          tokenPAT: ${{ secrets.PAT }} # `GH_PAT` is a secret that contains your PAT
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
