name: landscapes-workflow
'on':
  workflow_dispatch:
    inputs:
      selection:
        required: true
        description: Choose F for "Fernando de Noronha" or P for "Porto de Galinhas"
        type: choice
        options:
          - F
          - P
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    
    - name: Output using "echo"
      id: checkinputs
      run: echo "Se ha seleccionado '${{github.events.inputs.selection}}'"
      
    - name: Running the files 
      uses: santander-group-europe/test-spain-2022-html-action@master       
      id: actiontest
      with:
        selection: "${{github.events.inputs.selection}}"
        tokenPAT: ${{ secrets.PAT }} # `GH_PAT` is a secret that contains your PAT
