name: Universe vs World Test
'on':
  workflow_dispatch:
    inputs:
      hello:
        required: true
        description: Choose W for Hello world and U Hello universe
        type: choice
        options:
          - W
          - U
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    
   # - name: Checkout private tools
    #  uses: actions/checkout@v3
     # with:
      # token: ${{secrets.PAT}} # `GH_PAT` is a secret that contains your PAT
    
    - name: Action Test check input
      id: checkinputs
      run: "echo Se ha seleccionado '${{github.events.inputs.hello}}'"
      
    - uses: santander-group-europe/test-spain-2022-action@master
      name: Action Test        
      id: actiontest
      with:
        hello: "${{github.events.inputs.hello}}"
        token: ${{ secrets.PAT }} # `GH_PAT` is a secret that contains your PAT
