#Java app for testing
name: GitHub Actions Test
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check Java Version
        shell: bash
        run: java --version

