#Java app for testing
name: Hello Universe Test
on:
  workflow_dispatch :
    inputs:
        hello:
          required: true
          description: Choose country W for "Hello World!" or U for "Hello Universe!"          
          type: choice
          options: 
           - W
           - Y
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout private tools
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }} # `GH_PAT` is a secret that contains your PAT
    
      - name: Running the file
        shell: bash
        if: github.event.workflow_dispatch.inputs.hello == 'W'
        run: java HelloWorld.java
        
      - name: Running the file
        shell: bash
        if: github.event.workflow_dispatch.inputs.hello == 'U'
        run: java HelloUniverse.java
        
        
