#Java app for testing
name: Universe vs World Test
on:
#  push:
#    branches:
#      - master
#  pull_request:
#    branches:
#      - master
  workflow_dispatch:
    inputs:
        hello:
          required: true
          description: Choose W for "Hello World!" or U for "Hello Universe!"          
          type: choice
 #         default: 'W'
          options: 
           - W
           - U

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Action Test check input
        id: checkinputs
        run:
          echo "Se ha seleccionado ${{inputs.hello}}"
          
      - uses: santander-group-europe/test-spain-2022-action@master
        name: Action Test
        id: actiontest
        with:
          hello: "${{inputs.hello}}"

        
