name: universe-vs-world-workflow
'on':
  workflow_dispatch:
    inputs:
      hello:
        required: true
        description: Choose W for Hello world and U for Hello universe
        type: choice
        options:
          - W
          - U
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    
    - name: Action Test check input
      id: checkinputs
      run: "echo Se ha seleccionado '${{github.events.inputs.hello}}'"
      
    - name: Action Test 
      uses: santander-group-europe/test-spain-2022-action@master       
      id: actiontest
      with:
        hello: "${{github.events.inputs.hello}}"
        tokenPAT: ${{ secrets.PAT }} # `GH_PAT` is a secret that contains your PAT
